package com.mhub.scheduler.job;

import com.mhub.core.domain.entity.Tenant;
import com.mhub.core.domain.repository.TenantRepository;
import com.mhub.core.tenant.SchedulerTenantHelper;
import com.mhub.erp.service.ErpSalesDocumentService;
import com.mhub.erp.service.ErpSyncService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import net.javacrumbs.shedlock.spring.annotation.SchedulerLock;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;

@Slf4j
@Component
@RequiredArgsConstructor
public class NightlyBatchScheduler {

    private final TenantRepository tenantRepository;
    private final ErpSyncService erpSyncService;
    private final ErpSalesDocumentService erpSalesDocumentService;
    private final SchedulerTenantHelper schedulerTenantHelper;

    @Scheduled(cron = "0 0 2 * * *")
    @SchedulerLock(name = "nightlySettlementBatch", lockAtMostFor = "PT2H", lockAtLeastFor = "PT10M")
    public void runNightlySettlement() {
        log.info("Starting nightly settlement batch");
        for (Tenant t : tenantRepository.findByActiveTrue()) {
            try {
                schedulerTenantHelper.setTenant(t.getId());
                log.warn("Settlement batch for tenant {} skipped: not yet implemented", t.getId());
            } catch (Exception e) {
                log.error("Settlement failed for tenant {}", t.getId(), e);
            } finally {
                schedulerTenantHelper.clearTenant();
            }
        }
        log.info("Nightly settlement batch completed");
    }

    // 비활성화: 정산(Settlement) 단위 ERP 동기화는 레거시 방식으로, 현재 주문(Order) 단위 전표 생성 방식 사용
    // @Scheduled(cron = "0 30 2 * * *")
    // @SchedulerLock(name = "nightlyErpSync", lockAtMostFor = "PT2H", lockAtLeastFor = "PT10M")
    public void runNightlyErpSync() {
        log.info("Starting nightly ERP sync batch");
        for (Tenant t : tenantRepository.findByActiveTrue()) {
            try {
                schedulerTenantHelper.setTenant(t.getId());
                erpSyncService.syncUnsyncedSettlements(t.getId());
            } catch (Exception e) {
                log.error("ERP sync failed for tenant {}", t.getId(), e);
            } finally {
                schedulerTenantHelper.clearTenant();
            }
        }
        log.info("Nightly ERP sync batch completed");
    }

    /**
     * 자동 전표생성 및 ERP전송 배치 (매일 03:00)
     * - 각 테넌트의 ERP 설정에서 autoGenerateDocument, autoSendToErp 활성화 여부에 따라 처리
     * - autoGenerateDocument가 활성화된 경우: 배송중/배송완료 주문 중 전표 미생성 건에 대해 자동 전표 생성
     * - autoSendToErp가 활성화된 경우: 미전송(PENDING) 전표를 ERP로 자동 전송
     */
    @Scheduled(cron = "0 0 3 * * *")
    @SchedulerLock(name = "autoErpDocumentBatch", lockAtMostFor = "PT2H", lockAtLeastFor = "PT10M")
    public void runAutoErpDocumentBatch() {
        log.info("Starting auto ERP document batch (generate + send)");

        int totalGenerated = 0;
        int totalSent = 0;
        int processedTenants = 0;
        int skippedTenants = 0;

        for (Tenant t : tenantRepository.findByActiveTrue()) {
            try {
                schedulerTenantHelper.setTenant(t.getId());
                Map<String, Object> result = erpSalesDocumentService.processAutoErpBatch(t.getId());

                if (Boolean.TRUE.equals(result.get("skipped"))) {
                    log.debug("Auto ERP batch skipped for tenant {}: {}", t.getId(), result.get("reason"));
                    skippedTenants++;
                } else {
                    int generated = (int) result.getOrDefault("generatedCount", 0);
                    int sent = (int) result.getOrDefault("sentCount", 0);
                    totalGenerated += generated;
                    totalSent += sent;
                    processedTenants++;
                    log.info("Auto ERP batch for tenant {}: generated={}, sent={}", t.getId(), generated, sent);
                }
            } catch (Exception e) {
                log.error("Auto ERP batch failed for tenant {}", t.getId(), e);
            } finally {
                schedulerTenantHelper.clearTenant();
            }
        }

        log.info("Auto ERP document batch completed: processedTenants={}, skippedTenants={}, totalGenerated={}, totalSent={}",
                processedTenants, skippedTenants, totalGenerated, totalSent);
    }

    @Scheduled(cron = "0 0 3 1 * *")
    @SchedulerLock(name = "monthlyPartitionMaintenance", lockAtMostFor = "PT30M", lockAtLeastFor = "PT5M")
    public void runMonthlyPartitionMaintenance() {
        log.info("Starting monthly partition maintenance");
        log.warn("Monthly partition maintenance skipped: not yet implemented");
        log.info("Monthly partition maintenance completed");
    }
}
